'use strict';
const router = require('express').Router();

const authRouter = require('./auth');
const userRouter = require('./user');
const roleRouter = require('./role');
const permissionRouter = require('./permission');
const academic_yearRouter = require('./academic-year');
const termRouter = require('./term');
const classRouter = require('./class');
const subjectRouter = require('./subject');
const class_subjectRouter = require('./class-subject');
const scheduleRouter = require('./schedule');
const examRouter = require('./exam');
const gradeRouter = require('./grade');
const report_cardRouter = require('./report-card');
const studentRouter = require('./student');
const parentRouter = require('./parent');
const enrollmentRouter = require('./enrollment');
const attendanceRouter = require('./attendance');
const employeeRouter = require('./employee');
const payrollRouter = require('./payroll');
const leaveRouter = require('./leave');
const evaluationRouter = require('./evaluation');
const job_postingRouter = require('./job-posting');
const transactionRouter = require('./transaction');
const feeRouter = require('./fee');
const fee_paymentRouter = require('./fee-payment');
const budget_lineRouter = require('./budget-line');
const assetRouter = require('./asset');
const canteen_subscriptionRouter = require('./canteen-subscription');
const canteen_menuRouter = require('./canteen-menu');
const canteen_attendanceRouter = require('./canteen-attendance');
const transport_routeRouter = require('./transport-route');
const bookRouter = require('./book');
const book_loanRouter = require('./book-loan');
const book_reservationRouter = require('./book-reservation');
const health_recordRouter = require('./health-record');
const infirmary_visitRouter = require('./infirmary-visit');
const medical_stockRouter = require('./medical-stock');
const roomRouter = require('./room');
const room_reservationRouter = require('./room-reservation');
const clubRouter = require('./club');
const club_memberRouter = require('./club-member');
const eventRouter = require('./event');
const messageRouter = require('./message');
const notificationRouter = require('./notification');
const parent_meetingRouter = require('./parent-meeting');
const councilRouter = require('./council');
const council_decisionRouter = require('./council-decision');
const activity_logRouter = require('./activity-log');

// ── Health check ──────────────────────────────────────────────────────────────
router.get('/health', (req, res) => {
  res.json({ success: true, message: 'EduManage API v1 opérationnelle', timestamp: new Date().toISOString() });
});

// ── Modules ───────────────────────────────────────────────────────────────────
router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/roles', roleRouter);
router.use('/permissions', permissionRouter);
router.use('/academic-years', academic_yearRouter);
router.use('/terms', termRouter);
router.use('/classes', classRouter);
router.use('/subjects', subjectRouter);
router.use('/class-subjects', class_subjectRouter);
router.use('/schedules', scheduleRouter);
router.use('/exams', examRouter);
router.use('/grades', gradeRouter);
router.use('/report-cards', report_cardRouter);
router.use('/students', studentRouter);
router.use('/parents', parentRouter);
router.use('/enrollments', enrollmentRouter);
router.use('/attendances', attendanceRouter);
router.use('/employees', employeeRouter);
router.use('/payrolls', payrollRouter);
router.use('/leaves', leaveRouter);
router.use('/evaluations', evaluationRouter);
router.use('/job-postings', job_postingRouter);
router.use('/transactions', transactionRouter);
router.use('/fees', feeRouter);
router.use('/fee-payments', fee_paymentRouter);
router.use('/budget-lines', budget_lineRouter);
router.use('/assets', assetRouter);
router.use('/canteen-subscriptions', canteen_subscriptionRouter);
router.use('/canteen-menus', canteen_menuRouter);
router.use('/canteen-attendances', canteen_attendanceRouter);
router.use('/transport-routes', transport_routeRouter);
router.use('/books', bookRouter);
router.use('/book-loans', book_loanRouter);
router.use('/book-reservations', book_reservationRouter);
router.use('/health-records', health_recordRouter);
router.use('/infirmary-visits', infirmary_visitRouter);
router.use('/medical-stocks', medical_stockRouter);
router.use('/rooms', roomRouter);
router.use('/room-reservations', room_reservationRouter);
router.use('/clubs', clubRouter);
router.use('/club-members', club_memberRouter);
router.use('/events', eventRouter);
router.use('/messages', messageRouter);
router.use('/notifications', notificationRouter);
router.use('/parent-meetings', parent_meetingRouter);
router.use('/councils', councilRouter);
router.use('/council-decisions', council_decisionRouter);
router.use('/activity-logs', activity_logRouter);

module.exports = router;
